### ISSUE TITLE
Can not generate class diagram when selection many java files (classes)

### ISSUE THREAD

**Issue by Jamina2385** [hallvard/plantuml#173] opened 2023-09-02 15:33 UTC
Hello,

I started with plantuml to draw my class diagram on eclipe.

When i selected one class (java file), the entity class appears well in the plantuml window. But, when i selected more than one (example 2 classes), the plantUML window generates errors (...plantuml error rootcause net.sourceforge.plantuml.svek.EmptySvgException...) (see in attachement).

![plantUMLerror](https://github.com/hallvard/plantuml/assets/143893283/c414c591-ca50-451a-a3e0-7739fcb3597f)

I installed graphviz 2.44. I generated the dot.exe under \bin.

Have you any idea the source of this problem ?

Thank you,

**Comment by travkin79** [comment] 2024-04-10 15:18
Cannot reproduce the issue, no answer for quite some time. Thus, I close the issue.

**Closed by travkin79** 2024-04-10 15:18 UTC
