### ISSUE TITLE
Cannot open PlantUML view: StringUtils.isNotEmpty

### ISSUE THREAD

**Issue by hohwille** [hallvard/plantuml#170] opened 2023-04-24 09:33 UTC
When opening view `PlantUML` I get this error:
```
An internal error occurred during: "Generate diagram".
'boolean net.sourceforge.plantuml.StringUtils.isNotEmpty(java.lang.String)'
```

Environment:
> Eclipse IDE for Java Developers (includes Incubating components)
 Version: 2023-03 (4.27.0)
 Build id: 20230309-1520
   PlantUML Eclipse support	1.0.0.438ccNHSnh	net.sourceforge.plantuml.feature	null
    PlantUML Ecore Feature	1.1.26	net.sourceforge.plantuml.ecore.feature.feature.group	PlantUML Team
      PlantUML Feature	1.1.26	net.sourceforge.plantuml.feature.feature.group	PlantUML Team
      PlantUML Library Feature	1.2022.7	net.sourceforge.plantuml.lib.feature.feature.group	PlantUML Team

**Comment by travkin79** [comment] 2023-04-25 11:25
Can you reproduce that with PlantUML Eclipse plug-in 1.1.27, too? Is there a stacktrace in the Error Log View that you could provide or steps to reproduce?

**Comment by travkin79** [comment] 2024-04-10 15:21
I cannot reproduce the issue and there is no answer for quite a while. Thus, I close this issue.

**Closed by travkin79** 2024-04-10 15:21 UTC
