### ISSUE TITLE
exception running on openjdk11 with eclipse 4.10

### ISSUE THREAD

**Issue by richard-melvin** [hallvard/plantuml#81] opened 2019-02-04 16:40 UTC
Using:

Version: 2018-12 (4.10.0)
Build id: 20181214-0600

with

-vm
C:\Progra~1\OpenJDK\jdk-11.0.2\bin\javaw.exe

gets

```
ava.lang.NoClassDefFoundError: org/eclipse/jdt/internal/ui/javaeditor/IClassFileEditorInput
	at net.sourceforge.plantuml.jdt.ClassFileEditorDiagramTextProvider.getDiagramText(ClassFileEditorDiagramTextProvider.java:22)
	at net.sourceforge.plantuml.text.AbstractDiagramTextProvider.getDiagramText(AbstractDiagramTextProvider.java:41)
	at net.sourceforge.plantuml.text.AbstractDiagramTextProvider.getDiagramText(AbstractDiagramTextProvider.java:36)
	at net.sourceforge.plantuml.eclipse.views.AbstractDiagramSourceView.updateDiagramText(AbstractDiagramSourceView.java:305)
	at net.sourceforge.plantuml.eclipse.views.AbstractDiagramSourceView.updateDiagramText(AbstractDiagramSourceView.java:284)
	at net.sourceforge.plantuml.eclipse.views.AbstractDiagramSourceView$DiagramTextChangedListener.diagramChanged(AbstractDiagramSourceView.java:247)
	at net.sourceforge.plantuml.eclipse.views.AbstractDiagramSourceView$DiagramTextChangedListener.selectionChanged(AbstractDiagramSourceView.java:242)
	at org.eclipse.ui.internal.e4.compatibility.SelectionService.notifyListeners(SelectionService.java:242)
	at org.eclipse.ui.internal.e4.compatibility.SelectionService.handlePostSelectionChanged(SelectionService.java:116)
	at org.eclipse.ui.internal.e4.compatibility.SelectionService.lambda$2(SelectionService.java:71)

```

**Comment by hallvard** [comment] 2019-02-05 09:16
Duplicate of #77

**Closed by hallvard** 2019-02-05 09:16 UTC
